export enum postsTypes {
  POSTS_REQUIRED = "POSTS_REQUIRED",
  POSTS_SUCCESS = "POSTS_SUCCESS",
  POSTS_FAILED = "POSTS_FAILED",
  POSTS_PAGINATION_PAGE = "POSTS_PAGINATION_PAGE",
  POSTS_PAGINATION_LIMIT = "POSTS_PAGINATION_LIMIT",
}
